### ISSUE TITLE
Set date and title to "1970-01-01" if there is no date in file

### ISSUE THREAD

**Issue by peterpan192** [jgillula/paperless-ngx-postprocessor#26]
Hey there,
as stated in the title, I want the title and creation_date of files that have no dates in it to be set to "1970-01-01".
Paperless-ngx sets the creation_date to today's date if there is no date to be found so the post-processing-script should do something like 

if creation_date == today's date -> alter creation_date and title to 1970-01-01. How can I achieve this?

Here is my already working example.yaml. What it does: It sets title to whatever is the creation_date:

`All Documents Ruleset:
  match: True  # Always matches
  metadata_postprocessing:
    title: '{{created_year}}-{{created_month}}-{{created_day}}'
  selectors:
    - title`

**Comment by jgillula** [comment]
Try this and let me know if it works. 🙂

```yaml
Documents Created Today Ruleset:
  match: "{{ created_date_object == date.today() }}"
  metadata_postprocessing:
    created_year: "1970"
    created_month: "1"
    created_day: "1"
    title: '{{created_year}}-{{created_month}}-{{created_day}}'
```
